services:
  packetwatch:
    environment:
      PW_IFDEV: lo
      PW_WHITELIST_SELF: "True"

  tester:
    command: ["/usr/bin/python3", "e2e.py"] #only use a single process for e2e, because they're order-dependent.
    environment:
      PW_WHITELIST_SELF: "True"
                             
